version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment: 
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      EMAIL_FEEDBACK: email@email.com
      EMAIL_FEEDBACK_PW: password
      EMAIL_PORT: 465
      EMAIL_HOST: smtp.mail.yahoo.com
      EMAIL_SERVICE: yahoo

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres