# Default values for atlanters-anonymous.

replicaCount: 1

image:
  tag: deploy

ingress:
  hosts:
    - atlantersanonymous.dev.example.com
  tls:
   - secretName: atlanters-anonymous-deploy
     hosts:
       - atlantersanonymous.dev.example.com

config:
  dbHost: atlanters-anonymous-pg-deploy-postgresql
  dbSecret: atlanters-anonymous-pg-deploy-postgresql
  smtpSecret: atlanters-anonymous-smtp-deploy

