# Default values for atlanters-anonymous.

replicaCount: 1

image:
  repository: atlantbh/atlanters-anonymous
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    # whitelist ABH and GitHub hooks ranges
    nginx.ingress.kubernetes.io/whitelist-source-range: 77.77.214.216/30,192.30.252.0/22,185.199.108.0/22,140.82.112.0/20
  paths:
  - /
  hosts:
    - atlanters-anonymous.abhapp.com
  tls:
   - secretName: atlanters-anonymous
     hosts:
       - atlanters-anonymous.abhapp.com

config:
  dbHost: atlanters-anonymous-pg-postgresql
  dbSecret: atlanters-anonymous-pg-postgresql
  smtpSecret: atlanters-anonymous-smtp

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
