# Default values for atlanters-anonymous.

replicaCount: 2

image:
  repository: atlantbh/atlanters-anonymous
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    nginx.ingress.kubernetes.io/enable-access-log: "false"
  paths:
    - /
  hosts:
    - atlantersanonymous.example.com
  tls:
    - secretName: atlanters-anonymous
      hosts:
        - atlantersanonymous.example.com

config:
  dbHost: atlanters-anonymous-pg-postgresql
  dbSecret: atlanters-anonymous-pg-postgresql
  smtpSecret: atlanters-anonymous-smtp
  appSecret: atlanters-anonymous-app

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
